### ISSUE TITLE
false as default value of boolean type is not working

### ISSUE THREAD

**Issue by goodryanboy** [sharetribe/flex-cli#84]
I used this command

flex-cli search set --default=false  --key=sold --scope=public --type=boolean --marketplace=the-octopus-club-test

but as you can see in the default value its empty

<img width="1037" alt="Screen Shot 2020-10-29 at 2 59 35 PM" src="https://user-images.githubusercontent.com/26914582/97535932-5e9e9600-19f7-11eb-808f-cafba064370f.png">

**Comment by rap1ds** [comment]
Thanks for reporting! This should be fixed by #88
